apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: thoughts
    tier: backend
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: thoughts
    tier: backend
spec:
  selector:
    matchLabels:
      app: thoughts
      tier: backend
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
    spec:
      containers:
      - name: apigateway
        image: localhost:5000/thoughts/apigateway
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 200m
        env:
        - name: AUTH_SERVICE_ADDR
          value: authservice:5050
        - name: IMAGE_SERVICE_ADDR
          value: imageservice:8080
        - name: POST_SERVICE_ADDR
          value: postservice:5050
        - name: USER_SERVICE_ADDR
          value: userservice:5050
