apiVersion: v1
kind: Service
metadata:
  name: apiservice
spec:
  selector:
    app: thoughts
    tier: backend
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  labels:
    app: thoughts
    tier: backend
spec:
  selector:
    matchLabels:
      app: thoughts
      tier: backend
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
    spec:
      containers:
      - name: apiservice
        image: thoughts/apiservice
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_SERVICE_ADDR
          value: authservice:5050
        - name: POST_SERVICE_ADDR
          value: postservice:5050
        - name: USER_SERVICE_ADDR
          value: userservice:5050
        - name: IMAGE_SERVICE_ADDR
          value: imageservice:8080
