apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: thoughts
    tier: database
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: thoughts
    tier: database
spec:
  selector:
    matchLabels:
      app: thoughts
      tier: database
  template:
    metadata:
      labels:
        app: thoughts
        tier: database
    spec:
      containers:
      - name: database
        image: localhost:5000/thoughts/database
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 200m
        env:
        - name: POSTGRES_PASSWORD
          value: kubernetes
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: database-storage
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pv-claim
