apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: thoughts
    tier: frontend
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: thoughts
    tier: frontend
spec:
  selector:
    matchLabels:
      app: thoughts
      tier: frontend
  template:
    metadata:
      labels:
        app: thoughts
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: thoughts/frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
