apiVersion: v1
kind: Service
metadata:
  name: imageservice
spec:
  selector:
    app: thoughts
    tier: backend
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageservice
  labels:
    app: thoughts
    tier: backend
spec:
  selector:
    matchLabels:
      app: thoughts
      tier: backend
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
    spec:
      containers:
      - name: imageservice
        image: thoughts/imageservice
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /data/images
          name: image-storage
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: storage-pv-claim
