apiVersion: v1
kind: Service
metadata:
  name: postservice
spec:
  selector:
    app: thoughts
    tier: backend
  ports:
  - port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice
  labels:
    app: thoughts
    tier: backend
spec:
  selector:
    matchLabels:
      app: thoughts
      tier: backend
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
    spec:
      containers:
      - name: postservice
        image: thoughts/postservice
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:kubernetes@database:5432
