apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: thoughts
    tier: backend
  ports:
  - protocol: TCP
    port: 5010
    targetPort: 5010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: thoughts
    tier: backend
spec:
  selector:
    matchLabels:
      app: thoughts
      tier: backend
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
    spec:
      containers:
      - name: userservice
        image: thoughts/userservice
        imagePullPolicy: Never
        ports:
        - containerPort: 5010
        env:
        - name: PORT
          value: "5010"
        - name: DATABASE_URL
          value: postgresql://postgres:kubernetes@database:5432
        - name: AUTH_SERVICE_ADDR
          value: authservice:5010
