apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: thoughts
    tier: backend
  ports:
  - port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: thoughts
    tier: backend
spec:
  selector:
    matchLabels:
      app: thoughts
      tier: backend
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
    spec:
      containers:
      - name: userservice
        image: localhost:5000/thoughts/userservice
        ports:
        - containerPort: 5050
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 200m
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:kubernetes@database:5432
