# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import userservice.thoughts_pb2 as thoughts__pb2


class UserServiceStub(object):
  """*
  Services

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/thoughts.UserService/Create',
        request_serializer=thoughts__pb2.UserUpdates.SerializeToString,
        response_deserializer=thoughts__pb2.UserResponse.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/thoughts.UserService/GetUser',
        request_serializer=thoughts__pb2.UserRequest.SerializeToString,
        response_deserializer=thoughts__pb2.UserResponse.FromString,
        )
    self.UpdateUser = channel.unary_unary(
        '/thoughts.UserService/UpdateUser',
        request_serializer=thoughts__pb2.UserUpdates.SerializeToString,
        response_deserializer=thoughts__pb2.Status.FromString,
        )
    self.DeleteUser = channel.unary_unary(
        '/thoughts.UserService/DeleteUser',
        request_serializer=thoughts__pb2.UserRequest.SerializeToString,
        response_deserializer=thoughts__pb2.Status.FromString,
        )


class UserServiceServicer(object):
  """*
  Services

  """

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=thoughts__pb2.UserUpdates.FromString,
          response_serializer=thoughts__pb2.UserResponse.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=thoughts__pb2.UserRequest.FromString,
          response_serializer=thoughts__pb2.UserResponse.SerializeToString,
      ),
      'UpdateUser': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUser,
          request_deserializer=thoughts__pb2.UserUpdates.FromString,
          response_serializer=thoughts__pb2.Status.SerializeToString,
      ),
      'DeleteUser': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteUser,
          request_deserializer=thoughts__pb2.UserRequest.FromString,
          response_serializer=thoughts__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'thoughts.UserService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class FollowServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFollowing = channel.unary_unary(
        '/thoughts.FollowService/GetFollowing',
        request_serializer=thoughts__pb2.FollowersRequest.SerializeToString,
        response_deserializer=thoughts__pb2.Users.FromString,
        )
    self.GetFollowers = channel.unary_unary(
        '/thoughts.FollowService/GetFollowers',
        request_serializer=thoughts__pb2.FollowersRequest.SerializeToString,
        response_deserializer=thoughts__pb2.Users.FromString,
        )
    self.Follow = channel.unary_unary(
        '/thoughts.FollowService/Follow',
        request_serializer=thoughts__pb2.FollowRequest.SerializeToString,
        response_deserializer=thoughts__pb2.Status.FromString,
        )
    self.Unfollow = channel.unary_unary(
        '/thoughts.FollowService/Unfollow',
        request_serializer=thoughts__pb2.FollowRequest.SerializeToString,
        response_deserializer=thoughts__pb2.Status.FromString,
        )


class FollowServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetFollowing(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Follow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Unfollow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FollowServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFollowing': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowing,
          request_deserializer=thoughts__pb2.FollowersRequest.FromString,
          response_serializer=thoughts__pb2.Users.SerializeToString,
      ),
      'GetFollowers': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowers,
          request_deserializer=thoughts__pb2.FollowersRequest.FromString,
          response_serializer=thoughts__pb2.Users.SerializeToString,
      ),
      'Follow': grpc.unary_unary_rpc_method_handler(
          servicer.Follow,
          request_deserializer=thoughts__pb2.FollowRequest.FromString,
          response_serializer=thoughts__pb2.Status.SerializeToString,
      ),
      'Unfollow': grpc.unary_unary_rpc_method_handler(
          servicer.Unfollow,
          request_deserializer=thoughts__pb2.FollowRequest.FromString,
          response_serializer=thoughts__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'thoughts.FollowService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AuthServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Login = channel.unary_unary(
        '/thoughts.AuthService/Login',
        request_serializer=thoughts__pb2.Credentials.SerializeToString,
        response_deserializer=thoughts__pb2.AuthResponse.FromString,
        )
    self.Refresh = channel.unary_unary(
        '/thoughts.AuthService/Refresh',
        request_serializer=thoughts__pb2.AuthRequest.SerializeToString,
        response_deserializer=thoughts__pb2.AuthResponse.FromString,
        )
    self.Validate = channel.unary_unary(
        '/thoughts.AuthService/Validate',
        request_serializer=thoughts__pb2.AuthRequest.SerializeToString,
        response_deserializer=thoughts__pb2.Status.FromString,
        )
    self.ValidatePassword = channel.unary_unary(
        '/thoughts.AuthService/ValidatePassword',
        request_serializer=thoughts__pb2.Credentials.SerializeToString,
        response_deserializer=thoughts__pb2.Status.FromString,
        )


class AuthServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Refresh(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Validate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidatePassword(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=thoughts__pb2.Credentials.FromString,
          response_serializer=thoughts__pb2.AuthResponse.SerializeToString,
      ),
      'Refresh': grpc.unary_unary_rpc_method_handler(
          servicer.Refresh,
          request_deserializer=thoughts__pb2.AuthRequest.FromString,
          response_serializer=thoughts__pb2.AuthResponse.SerializeToString,
      ),
      'Validate': grpc.unary_unary_rpc_method_handler(
          servicer.Validate,
          request_deserializer=thoughts__pb2.AuthRequest.FromString,
          response_serializer=thoughts__pb2.Status.SerializeToString,
      ),
      'ValidatePassword': grpc.unary_unary_rpc_method_handler(
          servicer.ValidatePassword,
          request_deserializer=thoughts__pb2.Credentials.FromString,
          response_serializer=thoughts__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'thoughts.AuthService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SessionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSessions = channel.unary_unary(
        '/thoughts.SessionService/GetSessions',
        request_serializer=thoughts__pb2.AuthRequest.SerializeToString,
        response_deserializer=thoughts__pb2.Sessions.FromString,
        )
    self.DeleteSession = channel.unary_unary(
        '/thoughts.SessionService/DeleteSession',
        request_serializer=thoughts__pb2.SessionRequest.SerializeToString,
        response_deserializer=thoughts__pb2.Status.FromString,
        )


class SessionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSessions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSessions': grpc.unary_unary_rpc_method_handler(
          servicer.GetSessions,
          request_deserializer=thoughts__pb2.AuthRequest.FromString,
          response_serializer=thoughts__pb2.Sessions.SerializeToString,
      ),
      'DeleteSession': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSession,
          request_deserializer=thoughts__pb2.SessionRequest.FromString,
          response_serializer=thoughts__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'thoughts.SessionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
