apiVersion: v1
kind: Service
metadata:
  name: apiservice
spec:
  selector:
    app: thoughts
    tier: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
  labels:
    app: thoughts
    tier: backend
spec:
  selector:
    matchLabels:
      app: thoughts
      tier: backend
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
    spec:
      containers:
      - name: apiservice
        image: thoughts/apiservice
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
