apiVersion: v1
kind: Deployment
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
  - port: 5432
    name: database
  clusterIP: None
  selector:
    app: database
