apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  selector:
    app: thoughts
    tier: backend
  ports:
  - protocol: TCP
    port: 3200
    targetPort: 3200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: thoughts
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thoughts
      tier: backend
  template:
    metadata:
      labels:
        app: thoughts
        tier: backend
    spec:
      containers:
      - name: userservice
        image: thoughts/userservice
        imagePullPolicy: Never
        ports:
        - containerPort: 3200
        env:
        - name: PORT
          value: "3200"
