apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-pv-volume
  labels:
    app: thoughts
    tier: storage
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
